services:
  - type: web
    name: emotion-detection-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api.model_api:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"


